root: ./

redirects:
  audits-and-security: security/security.md
  community/factor-arms: socials/factor-arms.md
  factor-building-blocks/leverage/user-guides: factor-studio/studio-discover/leverage-user-guides/README.md
  factor-building-blocks/leverage/user-guides/manage-your-loan: factor-studio/studio-discover/leverage-user-guides/README.md
  factor-building-blocks/leverage/user-guides/refinance-your-loan: factor-studio/studio-discover/leverage-user-guides/README.md
  factor-building-blocks/leverage/user-guides/take-out-a-loan: factor-studio/studio-discover/leverage-user-guides/create-a-leveraged-position.md
  factor-discover: factor-studio/studio-discover.md
  factor-scale: governance/factor-scale/README.md
  factor-studio/discover: factor-studio/studio-discover.md
  faq/tokenomics: governance/fctr-token/faq-tokenomics.md
  faq/scale: governance/factor-scale/faq-factor-scale.md
  getting-started/use-cases: README.md
  getting-started/use-cases/allocators: README.md
  getting-started/use-cases/asset-managers-and-strategists: README.md
  getting-started/use-cases/builders: README.md
  getting-started/use-cases/defi-protocols: README.md
  getting-started/why-factor: README.md
  governance/factor-scale-for-vault-rewards: governance/factor-scale/README.md
  governance/getting-started-with-factor-scale: governance/factor-scale/README.md
  governance/vault-boosting-mechanism: governance/factor-boost.md
  governance-factor-scale/empowering-optimizing-and-encouraging-active-participation: governance/factor-scale/README.md
  governance-factor-scale/voting-and-boost-allocation: governance/factor-scale/README.md
  how-it-works: README.md
  important-links: README.md
  introducing-factor/key-features: README.md
  introducing-factor/key-differentiators: README.md
  products/leverage: factor-building-blocks/leverage/README.md
  products/yield: factor-building-blocks/yield/README.md
  products/yield/zap: factor-studio/factor-studio/README.md
  products/factor-studio: factor-studio/factor-studio/README.md
  community/factor-arms: community/factor-contributors.md
  tokenomics/staking-and-governance: governance/fctr-token/staking-and-governance.md
  tokenomics/scale: governance/factor-scale/README.md
  tokenomics/platform-fees: governance/fctr-token/platform-fees.md
  tokenomics/initial-distribution: governance/fctr-token/initial-distribution.md
  tokenomics/contract-addresses: governance/fctr-token/contract-addresses.md
  use-cases: README.md
  walkthroughs/leverage: factor-building-blocks/leverage/user-guides/README.md
  walkthroughs/governance-migration: governance/factordao/user-guides/migrate-from-v1-to-v2.md
